default_job = "check"

[jobs.check]
command = ["cargo", "check", "--manifest-path", "src-tauri/Cargo.toml"]
need_stdout = false

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--manifest-path",
  "src-tauri/Cargo.toml",
  "--all-targets",
  "--",
  "-D",
  "warnings",
]
need_stdout = false

[jobs.test]
command = ["cargo", "nextest", "run", "--manifest-path", "src-tauri/Cargo.toml"]
need_stdout = true
